name: PR Preview

on:
  schedule:
    - cron: 0 0 */6 * *
  pull_request_target:
    types: [closed]
  workflow_run:
    workflows: ["PR Preview Build"]
    types:
      - completed

concurrency:
  group: pr-preview
  cancel-in-progress: false

jobs:
  pr-preview-cache-refresh:
    if: ${{ github.event_name == 'schedule' && github.event.schedule == '0 0 */6 * *' }}
    runs-on: ubuntu-latest
    steps:
      - name: Cache Refresh
        uses: actions/cache/restore@v6
        with:
          key: pages-${{ github.run_id }}
          path: ${{ runner.temp }}/pages
          restore-keys: pages-
  pr-preview-remove:
    if: ${{ github.event_name == 'pull_request_target' && github.event.action == 'closed' }}
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      pull-requests: write
    env:
      PAGES_PATH: ${{ runner.temp }}/pages
      PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
    steps:
      - id: restore-pages
        name: Restore Pages
        uses: actions/cache/restore@v6
        with:
          key: pages-${{ github.run_id }}
          path: ${{ env.PAGES_PATH }}
          restore-keys: pages-
      - name: Prepare Pages
        run: |
          mkdir -p ${{ env.PAGES_PATH }}/data/{files,refs}
          rm -rf ${{ env.PAGES_PATH }}/PR${{ env.PULL_REQUEST_NUMBER }}
          grep -rlw 'PR${{ env.PULL_REQUEST_NUMBER }}' ${{ env.PAGES_PATH }}/data/refs | xargs -r sed -i '/\<PR${{ env.PULL_REQUEST_NUMBER }}\>/d'
          for ref in ${{ env.PAGES_PATH }}/data/refs/*; do
            if [ ! -s "$ref" ]; then
              base=$(basename "$ref")
              rm -f "${{ env.PAGES_PATH }}/data/files/$base"
              rm -f "$ref"
            fi
          done
          echo "[$(date)] Remove Preview PR${{ env.PULL_REQUEST_NUMBER }}" > ${{ env.PAGES_PATH }}/index.html
      - name: Save Pages
        uses: actions/cache/save@v6
        with:
          key: pages-${{ github.run_id }}
          path: ${{ env.PAGES_PATH }}
      - if: ${{ steps.restore-pages.outputs.cache-matched-key }}
        name: Remove History Cache
        uses: actions/github-script@v9
        with:
          script: |
            github.rest.actions.deleteActionsCacheByKey({
              owner: context.repo.owner,
              repo: context.repo.repo,
              key: "${{ steps.restore-pages.outputs.cache-matched-key }}"
            });
  pr-preview-deploy:
    if: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: https://${{ env.PREVIEW_DOMAIN }}${{ env.PREVIEW_PATHNAME }}/PR${{ env.PULL_REQUEST_NUMBER }}
    permissions:
      actions: write
      pages: write
      id-token: write
      contents: write
    env:
      PAGES_PATH: ${{ runner.temp }}/pages
      PREVIEW_DOMAIN: ${{ github.repository_owner }}.github.io
      PREVIEW_PATHNAME: ${{ github.event.repository.name != format('{0}.github.io', github.repository_owner) && format('/{0}', github.event.repository.name) || '' }}
    steps:
      - id: restore-pages
        name: Restore Pages
        uses: actions/cache/restore@v4
        with:
          key: pages-${{ github.run_id }}
          path: ${{ env.PAGES_PATH }}
          restore-keys: pages-
      - name: Merge Site Before
        run: |
          mkdir -p ${{ env.PAGES_PATH }}/data/{files,refs}
          rm -rf ${{ env.PAGES_PATH }}/PR${{ env.PULL_REQUEST_NUMBER }}
          grep -rlw 'PR${{ env.PULL_REQUEST_NUMBER }}' ${{ env.PAGES_PATH }}/data/refs | xargs -r sed -i '/\<PR${{ env.PULL_REQUEST_NUMBER }}\>/d'
      - name: Merge Site
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: artifact
          path: ${{ env.PAGES_PATH }}/PR${{ env.PULL_REQUEST_NUMBER }}
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Merge Site After
        run: |
          find ${{ env.PAGES_PATH }}/PR${{ env.PULL_REQUEST_NUMBER }} -type f | while read file; do
            hash=$(sha256sum "$file" | cut -d' ' -f1)
            size=$(stat -c%s "$file")
            key="${hash}-${size}"
            target="${{ env.PAGES_PATH }}/data/files/$key"
            if [ ! -f "$target" ]; then
              mv "$file" "$target"
            else
              rm -f "$file"
            fi
            ln -s "$(realpath --relative-to="$(dirname "$file")" "$target")" "$file"
            echo "PR${{ env.PULL_REQUEST_NUMBER }}" >> "${{ env.PAGES_PATH }}/data/refs/$key"
          done
          for ref in ${{ env.PAGES_PATH }}/data/refs/*; do
            if [ ! -s "$ref" ]; then
              base=$(basename "$ref")
              rm -f "${{ env.PAGES_PATH }}/data/files/$base"
              rm -f "$ref"
            fi
          done
          echo "[$(date)] Preview PR${{ env.PULL_REQUEST_NUMBER }}" > ${{ env.PAGES_PATH }}/index.html
      - id: upload-pages
        name: Upload Pages
        uses: actions/upload-pages-artifact@v4
        with:
          name: github-pages
          path: ${{ env.PAGES_PATH }}
      - name: Deploy Pages
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages
      - name: Save Pages
        uses: actions/cache/save@v4
        with:
          key: pages-${{ github.run_id }}
          path: ${{ env.PAGES_PATH }}
      - if: ${{ steps.restore-pages.outputs.cache-matched-key }}
        name: Remove History Cache
        uses: actions/github-script@v8
        with:
          script: |
            github.rest.actions.deleteActionsCacheByKey({
              owner: context.repo.owner,
              repo: context.repo.repo,
              key: "${{ steps.restore-pages.outputs.cache-matched-key }}"
            });
      - if: ${{ steps.upload-pages.outputs.artifact_id }}
        name: Remove Pages Artifact
        uses: actions/github-script@v8
        with:
          script: |
            github.rest.actions.deleteArtifact({
              owner: context.repo.owner,
              repo: context.repo.repo,
              artifact_id: "${{ steps.upload-pages.outputs.artifact_id }}",
            });
      - if: ${{ needs.preview-create-build.outputs.artifact-id }}
        name: Remove Temp Artifact
        uses: actions/github-script@v8
        with:
          script: |
            github.rest.actions.deleteArtifact({
              owner: context.repo.owner,
              repo: context.repo.repo,
              artifact_id: "${{ needs.preview-create-build.outputs.artifact-id }}"
            });
  pr-preview-deploy-comment:
    if: ${{ always() && needs.preview-create-init.result == 'success' }}
    needs: [preview-create-init, preview-create-deploy]
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
    steps:
      - if: ${{ github.event_name == 'issue_comment' }}
        id: comment-message
        name: Comment Message (issue_comment)
        env:
          PREVIEW_URL: https://${{ needs.preview-create-init.outputs.domain }}${{ needs.preview-create-init.outputs.pathname }}/PR${{ env.PULL_REQUEST_NUMBER }}
        continue-on-error: true
        uses: actions/github-script@v8
        with:
          script: |
            github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: context.payload.comment.id,
              issue_number: context.issue.number,
              body: "${{ needs.preview-create-deploy.result == 'success' && format('[Preview] {0}', env.PREVIEW_URL) || '[Preview] Failed, see logs for more information.' }}"
            });
      - if: ${{ steps.comment-message.outcome == 'failure' }}
        name: Comment Message
        env:
          PREVIEW_URL: https://${{ needs.preview-create-init.outputs.domain }}${{ needs.preview-create-init.outputs.pathname }}/PR${{ env.PULL_REQUEST_NUMBER }}
        uses: actions/github-script@v8
        with:
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: "${{ needs.preview-create-deploy.result == 'success' && format('[Preview] {0}', env.PREVIEW_URL) || '[Preview] Failed, see logs for more information.' }}"
            });
