name: Preview

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency:
  group: preview
  cancel-in-progress: false

env:
  JEKYLL_ENV: production
  PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
  PREVIEW_DOMAIN: neveler-test.github.io
  PREVIEW_PATHNAME: /HMCL-docs

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4"
      - name: Jekyll Build
        run: |
          echo "url: https://${{ env.PREVIEW_DOMAIN }}" > _action.yml
          echo "baseurl: ${{ env.PREVIEW_PATHNAME }}/PR${{ env.PULL_REQUEST_NUMBER }}" >> _action.yml
          echo "source: ${{ github.workspace }}" >> _action.yml
          echo "destination: /home/runner/site" >> _action.yml
          echo "preview:" >> _action.yml
          echo "  pr-number: ${{ env.PULL_REQUEST_NUMBER }}" >> _action.yml
          bundle install --jobs 4
          bundle exec jekyll build --trace --config _config.yml,_action.yml
      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: site
          path: /home/runner/site
