name: Preview

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency:
  group: preview
  cancel-in-progress: false

env:
  JEKYLL_ENV: production
  PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - id: init
        name: Init
        uses: actions/github-script@v8
        with:
          script: |
            const { owner, repo } = context.repo;
            const pages = (await github.rest.repos.getPages({ owner, repo })).data;
            const domain = pages.cname || `${owner.toLowerCase()}.github.io`;
            core.setOutput('domain', domain);
            core.setOutput('pathname', (pages.cname || repo.toLowerCase() === domain) ? '' : `/${repo}`);
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4"
      - name: Jekyll Build
        run: |
          echo "url: https://${{ steps.init.outputs.domain }}" > _action.yml
          echo "baseurl: ${{ steps.init.outputs.pathname }}/PR${{ env.PULL_REQUEST_NUMBER }}" >> _action.yml
          echo "source: ${{ github.workspace }}" >> _action.yml
          echo "destination: /home/runner/site" >> _action.yml
          echo "preview:" >> _action.yml
          echo "  pr-number: ${{ env.PULL_REQUEST_NUMBER }}" >> _action.yml
          bundle install --jobs 4
          bundle exec jekyll build --trace --config _config.yml,_action.yml
      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: site
          path: /home/runner/site
